micronaut:
  application:
    name: pixGrpc

grpc:
  server:
    port: ${SERVER_PORT:50051}
    keep-alive-time: 1h
    max-inbound-message-size: 1024

#-banco de dados
datasources:
  default:
    url: jdbc:postgresql://localhost:15432/pix
    driverClassName: org.postgresql.Driver
    username: postgres
    password: "@901256"
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update
  jpa.default.properties.hibernate.show_sql: true
  jpa.default.properties.hibernate.format_sql: true

itau:
  contas:
    url: `http://localhost:9091`

bcb:
  pix:
    url: `http://localhost:8082`


